- name: Upgrade all packages
  hosts: localhost
  connection: local
  become: yes
  tasks:
    - name: Run unattended upgrade with timeout
      command: >
        /usr/bin/apt-get dist-upgrade --yes --auto-remove
        -o Dpkg::Options::="--force-confdef"
        -o Dpkg::Options::="--force-confold"
      async: 600  # Maximum time the task is allowed to run (in seconds)
      poll: 5  
